<a href="https://colab.research.google.com/github/Betelgeuse4101/practice/blob/main/%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%9A%D0%BB%D0%B8%D0%BC%D0%BE%D0%B2_%D0%9A%D0%AD_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

# ЗАДАНИЕ 1
size = int(input('Введите кол-во элементов одномерного массива: '))     # размер массива
arr = np.array([np.random.randint(-70, 70) for i in range(size)])      # создание массива
print(arr)

def sort_array(arr: np.ndarray) -> np.ndarray:      # сортировка расческой (в лучшем случае О(nlogn), в худшем O(n^2))
  step = arr.size - 1
  while step > 0:
    for i in range(0, arr.size - step):
      if arr[i] > arr[i+step]:
        arr[i], arr[i+step] = arr[i+step], arr[i]
    step = int(step * 0.78)
  return arr
print(sort_array(arr))

Введите кол-во элементов одномерного массива: 25
[ 57 -68  52  55  15 -21 -48   9 -51  -7  46  60 -54 -16 -37 -58  17  53
  51  13  13 -13 -30 -44 -56]
[-68 -58 -56 -54 -51 -48 -44 -37 -30 -21 -16 -13  -7   9  13  13  15  17
  46  51  52  53  55  57  60]


In [ ]:
import numpy as np

# ЗАДАНИЕ 2
size1 = int(input('Введите размерность матрицы: '))    # Считывание размерности матрицы
def triangle_matrix(size: int) -> np.ndarray:
  matrix = np.asarray(np.eye(size1)).astype(int)   # матрица с единицами на главной диагонали
  for i in range(size):     # заполнение элементов правее диагонали единицами
    for j in range(size):
      if j > i:
        matrix[i, j] = 1
  return matrix
print(triangle_matrix(size1))

Введите размерность матрицы: 10
[[1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 1]]


In [ ]:
import numpy as np
import os
print(os.getcwd())

# ЗАДАНИЕ 3
def create_matrix_from_file(file: str) -> np.matrix:
  global lst_size    # список с размерностью матрицы А
  lst_size = []
  matrix = []
  with open(file, 'r') as f:
    lst_size = list(map(int, f.readline().split()))
    for line in f:
      row = list(map(float, line.strip().split()))   # Считывание матрицы из файла построчно
      matrix.append(row)
  print('Матрица А\n', np.asmatrix(matrix, dtype=np.float64))
  return np.asmatrix(matrix, dtype=np.float64)

def create_matrix_B(n, m) -> np.matrix:
  matrixB = np.asmatrix(np.random.randint(-50, 50, (lst_size[0], lst_size[1])), dtype=np.float64) # Создание случайной матрицы
  print('Матрица В\n', matrixB)
  return matrixB

def divide_by_min_elem(matrix: np.matrix) -> np.matrix:
  for row in matrix:
    min_nonzero = np.min(row[np.nonzero(row)])  # Минимальный элемент в строке
    row /= min_nonzero
  matrix1 = np.asmatrix(np.round(matrix, decimals=2))    # Округление элементов матрицы до сотых
  print('Матрица А после деления\n', matrix1)
  return matrix1

with open('result.txt', 'w') as f:
  matrixA = divide_by_min_elem(create_matrix_from_file('input.txt'))
  matrixB = create_matrix_B(lst_size[0], lst_size[1])
  matrixC = matrixB - matrixA
  f.write(str(matrixC))
print('Матрица С\n', matrixC)

/content
Матрица А
 [[ 5.  0.  4.  2.  3.  4.  2.]
 [ 0.  2.  3.  5.  7.  4. 25.]
 [45. 12.  0.  3. 56. 12. 21.]
 [12. 78. 98.  5. 52. 14. 14.]
 [ 6. 56. 12. 32. 45. 89. 14.]
 [ 5. 65. 12.  0. 32. 85. 65.]]
Матрица А после деления
 [[ 2.5   0.    2.    1.    1.5   2.    1.  ]
 [ 0.    1.    1.5   2.5   3.5   2.   12.5 ]
 [15.    4.    0.    1.   18.67  4.    7.  ]
 [ 2.4  15.6  19.6   1.   10.4   2.8   2.8 ]
 [ 1.    9.33  2.    5.33  7.5  14.83  2.33]
 [ 1.   13.    2.4   0.    6.4  17.   13.  ]]
Матрица В
 [[  8. -38.  -8. -45. -30. -18. -24.]
 [ 40. -10.  28.  44.  42.  -1. -50.]
 [ -8.  -6.  29.   5. -11.  42. -47.]
 [-17.   5. -35. -35.  10. -18.  -8.]
 [ -1. -24.  -7. -30.  28.  40.  31.]
 [-34. -45.  14. -16.  48. -23. -11.]]
Матрица С
 [[  5.5  -38.   -10.   -46.   -31.5  -20.   -25.  ]
 [ 40.   -11.    26.5   41.5   38.5   -3.   -62.5 ]
 [-23.   -10.    29.     4.   -29.67  38.   -54.  ]
 [-19.4  -10.6  -54.6  -36.    -0.4  -20.8  -10.8 ]
 [ -2.   -33.33  -9.   -35.33  20.5   

In [ ]:
import numpy as np

# Задание 4